services:
  - type: web
    name: voice-shopping-assistant
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      ./setup.sh
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
