services:
  - type: web
    name: voice-shopping-assistant
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      ./setup.sh
    startCommand: gunicorn app:app
